version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: rentflow-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/rentflow
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: rentflow-frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongo-data:
